name: Handle new issues

on:
  issues:
    types:
      - opened

jobs:
  set-labels:
    runs-on: ubuntu-latest
    steps:
     - name: Set issue defaults
       uses: meatlink/issue-defaults
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         label: new
         assignee: meatlink
